betagouv/signalement-app

- src/assets/data/anomalies.json
rajout "Fausse réduction de prix"
> modif base

- src/app/model/Anomaly.ts
- src/app/pages/report/category/category.component.ts
- src/assets/data/anomalies.json
La catégorie "Travail au noir" ne devait pas être affichée. Corrigé.
> Fix bug mots clés : catégorie affichée à tort

- src/assets/data/anomalies.yml
Modifs lien DGCCRF suite évolution SI
> MEP 13/09/19

- package-lock.json
- package.json
- server.ts
HTTP Strict Transport Security
X-Frame-Options
X-XSS-Protection
X-Content-Type-Options
> Implement various HTTP security policies using Helmet

- app.json
- src/app/model/CompanyAccess.ts
- src/app/pages/header/account-menu/account-menu.component.html
- src/app/pages/login/accesstoken.component.html
- src/app/pages/login/accesstoken.component.ts
- src/app/pages/secured/companies/mycompanies.component.html
- src/app/pages/secured/companies/mycompanies.component.ts
- src/app/pages/secured/companyaccesses/companyaccesses.component.html
- src/app/pages/secured/companyaccesses/companyaccesses.component.ts
- src/app/pages/secured/companyaccesses/invitation.component.html
- src/app/pages/secured/companyaccesses/invitation.component.ts
- src/app/pages/secured/secured.module.ts
- src/app/services/companyaccesses.service.ts
- src/app/services/report.service.ts
- src/assets/data/pages.json
Dépend de la màj back https://github.com/betagouv/signalement-api/pull/132
> Update company access page based on review

- src/app/pages/login/forget-password/forgot-password.component.html
- src/app/pages/login/login.component.html
- src/app/pages/login/login.component.ts
- src/app/pages/login/reset-password/reset-password.component.html
- src/app/pages/report/company/company.component.html
- src/app/pages/secured/dgccrf/dgccrf.component.html
- src/app/pages/secured/reports/detail/report-detail.component.html
- src/app/pages/secured/reports/list/report-list.component.html
- src/app/pages/secured/reports/ordered/most-reported-list.component.html
- src/app/pages/static/pro/pro.component.html
- src/app/services/analytics.service.ts
* Ajout d'un message en cas d'échec d'activation
* Uniformisation Siret => SIRET
* Affichage de l'email dans les liens (**À VALIDER**)
> Activation error msg

- src/app/pages/report/details/details.component.spec.ts
- src/app/pages/report/details/details.component.ts
Y a-t-il des endroits où il faut le rajouter du coup @jrivals  ?
> Remove time input from default widgets

- app.json
- src/app/model/AuthUser.ts
- src/app/pages/account/account-registration/account-registration.component.html
- src/app/pages/account/account-registration/account-registration.component.ts
- src/app/pages/account/account.module.ts
- src/app/pages/companies/company-activation/company-activation.component.ts
- src/app/pages/header/account-menu/account-menu.component.html
- src/app/pages/secured/admin/admin.component.html
- src/app/pages/secured/admin/admin.component.ts
- src/app/pages/secured/secured.module.ts
- src/app/services/account.service.ts
- src/app/services/authentication.service.ts
- src/assets/data/pages.json
Pour que l'app soit compatible avec les tokens sans siret, et avec un kind.
> Generic tokens

- app.json
- package-lock.json
- package.json
- src/app/app.module.ts
- src/environments/environment.prod.ts
- src/environments/environment.ts
> Log front errors in Sentry

- src/app/components/attachments/attachments.component.ts
- src/app/services/keyword.service.ts
Not supported on IE
See https://sentry.data.gouv.fr/signalconso-um/signalconso-app/issues/1873988/
> includes => indexOf(...) != -1

- src/assets/data/anomalies.yml
- src/assets/data/subcategories/sante.yml
- src/assets/data/subcategories/services-aux-particuliers.yml
- src/assets/data/subcategories/voyage-loisirs.yml
Fix orthography and syntax rules
> MEP 17/02/20 #4

- src/app/pages/companies/companies.module.ts
Add url "/activation" to be compliant with activation document which are sent to pro
> MEP 21/02/20 #2

- src/app/model/ReportFilter.ts
- src/app/pages/secured/reports/list/report-list.component.html
- src/app/services/report.service.ts
À discuter. Le formulaire est un peu lourd.
@jrivals si ça te semble pertinent on peut mettre un "collapse", mais d'un autre côté ça rajoute un clic pour déplier le formulaire, ce que personnellement je trouve pénible :)
> Filter reports by email

- src/app/pages/companies/companies.module.ts
Restore account activation URL
> MEP 17/04/20

- src/app/pages/static/faq/faq.component.html
Quelques modifs de la FAQ : propositions de reformulations et ajout de la notion d'adresse mail nécessaire pour l'activation du compte (#nouvelle activation)
> "Update FAQ"

- server.ts
This reverts commit ec061f6bbc267eeec75709ef918aac6230f26876 ("Update CSP to be more specific about *.data.gouv.fr")
> MEP 02/10/20

- src/app/pages/report/company/company.component.html
- src/app/pages/report/company/company.component.ts
and then navigate directly on confirmation page
> Fix issue when aborting a company change

- src/app/pages/companies/companies-admin/companies-admin.component.html
- src/app/pages/companies/company-card/company-card.component.html
- src/app/pages/reports/reports.module.ts
Since siret filter is group with the other: by query string.
> Fix: Redirection to signalement by SIRET

- src/app/pages/manage-websites/manage-websites.component.scss
- src/app/pages/manage-websites/manage-websites.component.ts
- src/app/pages/reports/list/datatable/report-list-datatable.component.scss
- src/app/pages/reports/list/datatable/report-list-datatable.component.ts
- src/app/pages/reports/list/report-list.component.spec.ts
- src/app/pages/static/about/about.component.spec.ts
- src/assets/data/pages.json
- src/theme/utils.scss
- Allow siret text selection
- Table overflow
- Add titles
- Fix filters issues on refresh
> Manage websites: Fix minors issues

- src/app/pages/static/contact/contact.component.html
- src/app/pages/static/contact/contact.component.ts
useless since internet reports are now allowed
> Remove internet section in contact page

- src/app/pages/report/company/foreign-country/company-foreign-country.component.html
- src/app/pages/report/company/foreign-country/company-foreign-country.component.ts
to prevent unexplained prod issue
> Recheck country value before submitting
